### ISSUE TITLE
LinearGAM gridsearch is slow

### ISSUE THREAD

**Issue by josef821** [TomStog/curved-text-alignment#3]
hi. thanks for sharing your code.
it works great.
is there any faster alternative for LinearGAM library or gridsearch function? it takes 1 second to run and it will make ocr slow (for example run for 20 line in one image)

**Comment by TomStog** [comment]
Thank you very much, I'm glad that my code helped you. I looked into the LinearGAM documentation and I think the change I made has given it a significant speed boost.

**Comment by TomStog** [comment]
I would love to see any examples you can share.

**Comment by josef821** [comment]
Did you update the codes? so fast? you are amazing. Its speed has changed from 1 second to 0.06 seconds and this is very great. If you can fix the part where you save the file as Excel and read it again, I think the speed of the whole program will be multiplied. In fact, use a variable instead of a file.
