### ISSUE TITLE
Correcting incomplete curvature

### ISSUE THREAD

**Issue by josef821** [TomStog/curved-text-alignment#4]
i try to fix this this curve image:
![output png_tresh](https://github.com/TomStog/curved-text-alignment/assets/9824705/3c81c59b-f0a0-4bda-baf5-d9913c98a050)

it found red line very good:
![Screenshot 2024-03-17 175241](https://github.com/TomStog/curved-text-alignment/assets/9824705/0fe061ec-72bb-43a0-aac1-20a10a0f237d)

this is output image:
![Screenshot 2024-03-17 175248](https://github.com/TomStog/curved-text-alignment/assets/9824705/35573a60-253e-4ee3-8101-7a2a47dcbd6c)

The algorithm you wrote needs some changes due to the large curvature. In fact, the middle of the curve is correctly smoothed( "S" character was uncurved correctly), but the left and right sides are not smoothed well.
In an article titled "Alignment of Curved Text Strings for Enhanced
"OCR Readability" worked like this. Can you make changes like this?
![Screenshot 2024-03-18 130251](https://github.com/TomStog/curved-text-alignment/assets/9824705/9574c328-925b-47c9-b0dd-39c178260aa1)

**Comment by TomStog** [comment]
My project was developed for a competition hosted by a technology company, focusing on the processing of scanned documents. These input images consisted exclusively of text lines, featuring only slight curvatures, like the one featured at the "Greek Text Example" section.

**Comment by josef821** [comment]
Do you have a plan to fix this problem? Or do you not intend to develop this program? I am writing an OCR and your program is very important to me. Only if you can draw a spline like the last photo and make the curve based on the spline, it would be great.

**Comment by TomStog** [comment]
Hold up, you' re talking about a commercial OCR app/program ?

**Comment by josef821** [comment]
No. For my university project for my bachelor's degree, I chose the subject of OCR and I am examining the challenges that arise in creating this program and I am doing it practically to present to my professor.
I tested different algorithms, but none of them were as fast and good as your algorithm. But this problem that I said exists in it and it would be great if you could solve this too so that I can put the name and link of your project in my project.
The code you wrote can be useful for many people and is a good source for solving the problem of curvature in images. It is also a very good resume for you.

**Comment by TomStog** [comment]
What you're describing is advanced image processing/dewarping, a field I'm not able to study right now because I'm in the middle of my PhD in a different subject. I'm sorry but I can't be of assistance at the time being. I wish you all the best for your project.

**Comment by TomStog** [comment]
![sports](https://github.com/TomStog/curved-text-alignment/assets/82231949/810c5487-0e64-4d12-8757-589a7ad9ab59)
![sports_output](https://github.com/TomStog/curved-text-alignment/assets/82231949/d7e6e224-52c7-4641-b7d1-74ebc5fb9744)
![sports_output_final](https://github.com/TomStog/curved-text-alignment/assets/82231949/dd55c28f-bede-4e17-867a-4bf0e812b6e2)

**Comment by TomStog** [comment]
I'll spend the next few days polishing the code before finally uploading it. If you are interested, you can help me optimizing it.

**Comment by josef821** [comment]
it's very good. thanks but i'm not professional like you in computer vision and ai.
But I am proud to be able to help.
how can i help? share code to check.

**Comment by TomStog** [comment]
The code and the "sports.png" image have been uploaded. It's not optimized yet and there are some parameters that are manually changed. That's the next step in order to fully automate it.

**Comment by josef821** [comment]
did you do this with "Alignment of Curved Text Strings for Enhanced
"OCR Readability" article? or you create your own algorithm?
explain to solve it together

**Comment by TomStog** [comment]
It is an algorithm of my own. I start with the red line and for every point I calculate perpendicular points to the estimated curve. Something like this :
![Figure_1](https://github.com/TomStog/curved-text-alignment/assets/82231949/c5501982-de05-4307-832d-f347fbdc92e0)

Then using Bresenham's line algorithm, connecting the two perpendicular points, I take all the in-between pixels and use them to create the new image. Finally, I use my old standard algorithm to straighten any deformations.

Overall, it's like scanning up and down across the estimated curve.

**Comment by josef821** [comment]
greate.
i working on source code and check them line by line.
seems i need much more time than you 😄

**Comment by TomStog** [comment]
Are you interested in writing a paper about this ?
